#Minecraft server properties
#Fri Jul 10 00:23:51 UTC 2026
accepts-transfers=true
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=80
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=100000
max-players=35
max-tick-time=60000
max-world-size=4000001
motd=RumahKita S2
network-compression-threshold=512
online-mode=false
op-permission-level=4
pause-when-empty-seconds=0
player-idle-timeout=0
prevent-proxy-connections=false
query.port=22044
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://download.mc-packs.net/pack/0509cf0244c3b4f23fc378cadd7fcfd073fc4bcd.zip
resource-pack-id=9da99ad6-23e3-4a49-a737-b7765d8ad083
resource-pack-prompt={"text"\:"Our server uses a custom resource pack\!", "color"\:"gold"}
resource-pack-sha1=0509cf0244c3b4f23fc378cadd7fcfd073fc4bcd
server-ip=0.0.0.0
server-port=22044
simulation-distance=6
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=7
white-list=true
