name: RumahKitaWarps
version: 1.0.0
main: id.rumahkita.warps.RumahKitaWarpsPlugin
api-version: 1.13
depend:
- RumahKitaEconomyV2
commands:
  pwarp:
    description: Player Warp Commands
    aliases:
    - pw
    - playerwarp
    usage: /pwarp <set/delete/list>
  rtp:
    description: Random teleport to a random location
    aliases:
    - tpr
    usage: /rtp
  back:
    description: Return to previous location or death point
    usage: /back
  rkw:
    description: RumahKitaWarps Admin Command
    usage: /rkw
    permission: rumahkitawarps.admin
  warp:
    description: Open warp menu
    aliases:
    - warps
    usage: /warp [nama]
  setwarp:
    description: Create server warp
    usage: /setwarp <nama>
    permission: rumahkitawarps.admin
  delwarp:
    description: Delete server warp
    usage: /delwarp <nama>
    permission: rumahkitawarps.admin
  editwarp:
    description: Edit warp (icon, slot, lore)
    usage: /editwarp <nama> <icon/slot/lore> <value>
    permission: rumahkitawarps.admin
