name: RumahKitaPvP1v1
version: 1.0.2
main: id.rumahkita.pvp.RumahKitaPvP1v1Plugin
api-version: '1.13'
author: RumahKita
folia-supported: false
commands:
  pvp:
    description: RumahKita PvP 1v1 arena system
    usage: /pvp
    aliases: [duel, rkduel, rkpvp]
permissions:
  rumahkita.pvp.use:
    default: true
  rumahkita.pvp.admin:
    default: op
  rumahkita.pvp.bypass:
    default: op
