name: RumahKitaRestart
version: 1.0.0
main: id.rumahkita.restart.RumahKitaRestartPlugin
api-version: 1.13

commands:
  rkar:
    description: "Manage Auto Restart"
    aliases: [autorestart, rkrestart]
    permission: rkrestart.admin
