name: RumahKitaGames
version: 1.0.0
main: id.rumahkita.games.RumahKitaGamesPlugin
api-version: 1.13
depend: [RumahKitaEconomyV2]

commands:
  coinflip:
    description: "Main lempar koin taruhan uang"
    aliases: [cf, rkcf]
    usage: "/coinflip <create/join/cancel> [amount] [heads/tails]"
  rps:
    description: "Main batu gunting kertas taruhan uang"
    aliases: [suwit, rps]
    usage: "/rps <create/join/cancel> [amount/player] [batu/gunting/kertas]"
  rkg:
    description: "Command admin RumahKitaGames"
    permission: rumahkita.admin
    usage: "/rkg reload"
